name: Run PyTest and Flake8

on:
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Run PyTest
      run: |
        pytest 
      env:
        PYTHONPATH: ${{ github.workspace }}

    - name: Run Flake8
      run: |
        flake8 --exit-zero --extend-ignore=E,F,W

    # Flake8 step continues on error
    - name: Check Flake8 results
      continue-on-error: true
      run: echo "Flake8 check completed."
      env:
        PYTHONPATH: ${{ github.workspace }}