name: Run PyTest and Flake8

on:
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  

    - name: Run PyTest
      run: |
        pytest 
      env:
        PYTHONPATH: ${{github.workspace}}

    - name: Run Flake8
      run: |
        # Check for Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Treat all errors as warnings with a maximum line length of 127 characters
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      env:
        PYTHONPATH: ${{github.workspace}}    